name: CI - Admin Guardrail for Main Branch

on:
  push:
    branches:
      - main

jobs:
  prevent_direct_push:
    name: Prevent Direct Push to Main
    # This job runs if the push was NOT from our release bot and was NOT a merge commit.
    if: |
      github.event.pusher.name != 'github-actions[bot]' &&
      !startsWith(github.event.head_commit.message, 'chore(release):') &&
      github.event.head_commit.committer.name != 'web-flow'
    runs-on: ubuntu-latest
    steps:
      - name: Fail the build
        run: |
          echo "ERROR: A direct push to the 'main' branch was detected."
          echo "This is a policy violation. All changes must be submitted via a pull request."
          exit 1
