name: CI - Pull Request Quality Gate

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # This job is our critical safety net for administrators.
  prevent_direct_push:
    name: Prevent Direct Push to Main
    # FIX: Add a fourth condition to ignore merge commits from the web UI.
    # This job now only runs if the push is from a non-bot, non-release,
    # AND non-web-flow (i.e., a direct git push) event.
    if: |
      github.event_name == 'push' &&
      github.event.pusher.name != 'github-actions[bot]' &&
      !startsWith(github.event.head_commit.message, 'chore(release):') &&
      github.event.head_commit.committer.name != 'web-flow'
    runs-on: ubuntu-latest
    steps:
      - name: Fail the build
        run: |
          echo "ERROR: Direct push to 'main' by an administrator is not allowed by policy."
          echo "All changes must be submitted via a pull request."
          exit 1

  quality_gate:
    name: PR Quality Gate
    # This job ONLY runs on pull request events.
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Linter on Affected Projects
        run: npx nx affected --target=lint --base=origin/main --head=HEAD

      - name: Run Tests on Affected Projects
        run: npx nx affected --target=test --base=origin/main --head=HEAD

      - name: Build Affected Projects
        run: npx nx affected --target=build --base=origin/main --head=HEAD

