name: CI - Pull Request Quality Gate

# This workflow runs on all pull requests targeting the 'main' branch.
on:
  pull_request:
    branches:
      - main
  # This section provides our "safety net" to detect direct pushes to main.
  push:
    branches:
      - main

jobs:
  # This job only runs on direct pushes to main and will fail if the commit
  # did not come from a merged pull request.
  prevent_direct_push:
    name: Prevent Direct Push to Main
    if: github.event_name == 'push' && github.event.pusher.name != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Check for associated pull request
        uses: xt0rted/pull-request-comment-branch@v1
        id: check_pr
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fail if no PR is found
        if: steps.check_pr.outputs.pull_request_number == ''
        run: |
          echo "ERROR: Direct push to 'main' is not allowed."
          echo "All changes must be submitted via a pull request."
          exit 1

  # This is our main quality gate that runs on all pull requests.
  quality_gate:
    name: PR Quality Gate
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # We need to fetch the full history to allow Nx to run 'affected' commands
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      # FIX: Use 'nx affected' to run tasks only on projects impacted by the PR.
      # This is the key to a scalable monorepo CI.
      - name: Run Linter on Affected Projects
        run: npx nx affected --target=lint --base=origin/main --head=HEAD

      - name: Run Tests on Affected Projects
        run: npx nx affected --target=test --base=origin/main --head=HEAD

      - name: Build Affected Projects
        run: npx nx affected --target=build --base=origin/main --head=HEAD

